version: '3.1'

services:

  db:
    image: arm32v7/postgres:15.0
    restart: always
    environment:
      POSTGRES_PASSWORD: $METEO_DB_PASS
      POSTGRES_DB: $METEO_DB_NAME
      POSTGRES_USER: $METEO_USER
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/alexey/db/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    container_name: postgres 

  adminer:
    image: arm32v7/adminer:4.8.1
    restart: always
    ports:
      - 8080:8080
    container_name: adminer
